### ISSUE TITLE
FATAL ERROR: JavaScript heap out of memory

### ISSUE THREAD

**Issue by rainabba** [modesty/pdf2json#119]
version 1.1.7

My app works fine on smaller PDFs, but when I try on the one I need (10MB, 1000 pages that I'm breaking into many), the Node app goes north of 1.6GB ram and then crashes and the output makes me think the cause is in pdffont.js. If it's relevant, I do embed fonts in my PDFs.

> <--- Last few GCs --->
> 
>    98650 ms: Mark-sweep 1090.3 (1434.3) -> 1089.7 (1434.3) MB, 915.4 / 0.0 ms [allocation failure] [GC in old space requested].
>    99489 ms: Mark-sweep 1089.7 (1434.3) -> 1089.7 (1434.3) MB, 838.7 / 0.0 ms [allocation failure] [GC in old space requested].
>   100346 ms: Mark-sweep 1089.7 (1434.3) -> 1097.1 (1404.3) MB, 856.9 / 0.0 ms [last resort gc].
>   101258 ms: Mark-sweep 1097.1 (1404.3) -> 1104.7 (1404.3) MB, 912.4 / 0.0 ms [last resort gc].
> 
> 
> <--- JS stacktrace --->
> 
> ==== JS stack trace =========================================
> 
> Security context: 00000300657CFB49 <JS Object>
>     1: processText [ node_modules\pdf2json\lib\pdffont.js:~321] [pc=0000015911B07E12] (this=000002D2574FC711 <a cls with map 000002078631DF89>,p=000003FCA3EFF4E9 <an Object with map 0000020786341DF1>,str=0000030065749301 <String[1]: m>,maxWidth=000003FCA3EFFFE1 <Number: 11.611>,color=000003FCA3EFD199 <String[7]: #000000>,fontSize=000003FCA3EFFFF1 <Number: 20>,...
> 
> FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory

**Comment by rainabba** [comment]
Here's a more complete trace

> FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
>  1: node::Abort() [node]
>  2: 0x10a598c [node]
>  3: v8::Utils::ReportApiFailure(char const*, char const*) [node]
>  4: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [node]
>  5: v8::internal::Factory::NewFixedArray(int, v8::internal::PretenureFlag) [node]
>  6: v8::internal::TypeFeedbackVector::New(v8::internal::Isolate*, v8::internal::Handle<v8::internal::TypeFeedbackMetadata>) [node]
>  7: 0xb49850 [node]
>  8: 0xb49e43 [node]
>  9: 0xb4c180 [node]
> 10: 0xb53a86 [node]
> 11: v8::internal::Compiler::Compile(v8::internal::Handle<v8::internal::JSFunction>, v8::internal::Compiler::ClearExceptionFlag) [node]
> 12: v8::internal::Runtime_CompileLazy(int, v8::internal::Object**, v8::internal::Isolate*) [node]
> 13: 0x2c8ca26092a7

**Comment by rainabba** [comment]
Here's output from a node --prof-process from --prof. Little doubt where the crash is coming from. Question is if it's somehow specific to the PDF I'm using or otherwise resulting from my code.

>  [Summary]:
>    ticks  total  nonlib   name
>   24405   14.2%   15.3%  JavaScript
>   128699   75.0%   80.5%  C++
>   35709   20.8%   22.3%  GC
>   11651    6.8%          Shared libraries
>    6809    4.0%          Unaccounted

> 1336    0.8%    0.8%  LazyCompile: *matrixMultiply /mnt/c/prj/AZPREP/GIT/WEB/BatchManWeb/node_modules/pdf2json/lib/pdfcanvas.js:37:28


>    3624    2.1%  /usr/bin/nodejs
>     719   19.8%    v8::internal::Runtime_KeyedGetProperty(int, v8::internal::Object**, v8::internal::Isolate*)
>     445   61.9%      LazyCompile: *CanvasGraphics_executeOperatorList :40524:69

>    5054    2.9%  [vdso]
>    4126   81.6%    /usr/bin/nodejs
>    4005   97.1%      LazyCompile: *CanvasGraphics_executeOperatorList :40524:69
>    3870   96.6%        LazyCompile: *InternalRenderTask__continue :43540:53
>    3606   93.2%          LazyCompile: *ontimeout timers.js:361:19
>    3606  100.0%            LazyCompile: tryOnTimeout timers.js:233:22

> [Bottom up (heavy) profile]:
>   Note: percentage shows a share of a particular caller in the total
>   amount of its parent calls.
>   Callers occupying less than 2.0% are not shown.
> 
>    ticks parent  name
>   53128   31.0%  write
>   34065   64.1%    /usr/bin/nodejs
>   33311   97.8%      LazyCompile: *CanvasGraphics_executeOperatorList :40524:69

[procsesed.txt](https://github.com/modesty/pdf2json/files/956445/procsesed.txt)

**Comment by ldenoue** [comment]
I made a c++ version based on xpdf.
Should run fine on large PDFs.
You can span the binary from NodeJS.
https://github.com/ldenoue/pdftojson

**Comment by kennylbj** [comment]
Any other solutions for large PDF?

**Comment by albanirneves** [comment]
In my case this is the error:

`<--- Last few GCs --->

[6008:00000029B14A0010] 54118607 ms: Mark-sweep 438.0 (451.5) -> 437.9 (451.5) MB, 664.9 / 3.3 ms  (average mu = 0.324,
current mu = 0.034) external memory pressure GC in old space requested
[6008:00000029B14A0010] 54119397 ms: Mark-sweep 438.0 (451.5) -> 437.9 (451.5) MB, 649.2 / 3.3 ms  (average mu = 0.263,
current mu = 0.179) external memory pressure GC in old space requested


<--- JS stacktrace --->

FATAL ERROR: Committing semi space failed. Allocation failed - JavaScript heap out of memory
 1: 00007FF7166F2E7F
 2: 00007FF716681EC6
 3: 00007FF716682D7D`

**Comment by Milesssssss** [comment]
node --max-old-space-size=4096 yourscript.js
