### ISSUE TITLE
x, y and width units ?

### ISSUE THREAD

**Issue by SPlatten** [modesty/pdf2json#123]
First off, well done on the module, it works well.  I've looked at the 'readme.md' and it says that x and y are in page units, what does this mean?

I would like to use a ruler with a printed version of a document I've imported to check the co-ordinates, this is important as I want to create a form where the use can specify the co-ordinates of text to extract.

I assume they were in mm, but is doesn't appear to be the case.

**Comment by SPlatten** [comment]
Found this:

https://www.leadtools.com/help/leadtools/v19m/dh/to/pdf-topics-pdfcoordinatesystem.html

**Comment by RST-J** [comment]
You are on the right track. The unit is [typography points](https://en.wikipedia.org/wiki/Point_(typography)).

I'm not sure whether there are PDFs for which different parsing libraries would detect different medium sizes (the pdftk utilitie's dump_data operation might also be interesting for you). I rather suspect that this is not the case.
But I can well imagin different PDF creation tools to decide on a different number of points when converting standard format sizes to points, so in my projects I allow a certain range to be valid here (for A4 I have I think a range covering 5 points).

**Comment by SPlatten** [comment]
Thank you, I will take a look.

**Comment by SPlatten** [comment]
Hi, I'm still struggling with the units and translating, I've tried using GIMP, loading the PDF and trying the various measurement units, but none of these agree or match up with what is reported in the produced JSON.

Its absolutely critical to the success of out project that we know and understand the units in the PDF/JSON, as we need to be able to identify content in the PDF based on co-ordinates.

How to you calculate the x and y positions ?  I could take a look at the source, but it would be easier if you could explain, thank you for your time.

**Comment by RST-J** [comment]
I have no ready-to-use node.js environment at hand. If you can give me a sample PDF file and the pdf2json output for that file as JSON file I'll take some time to reconstruct that.
I still have to deal with PDFs and position based parsing and such, so'll I guess its worth a try. But I can't promise, however. ;)

**Comment by SPlatten** [comment]
Thank you,

Please find attached the original PDF and the JSON produced.

Kind Regards,



Simon Platten
simonaplatten@gmail.com

**Comment by SPlatten** [comment]
Thank you,

Please find attached the original PDF and the JSON produced.

Kind Regards,



Simon Platten
simonaplatten@gmail.com



On 15 May 2017, at 19:53, Jonas Peschla <notifications@github.com> wrote:

I have no ready-to-use node.js environment at hand. If you can give me a
sample PDF file and the pdf2json output for that file as JSON file I'll
take some time to reconstruct that.
I still have to deal with PDFs and position based parsing and such, so'll I
guess its worth a try. But I can't promise, however. ;)

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/modesty/pdf2json/issues/123#issuecomment-301569537>,
or mute
the thread

**Comment by SPlatten** [comment]
Any update?

**Comment by RST-J** [comment]
You answered the comment by mail and attached the two files, right? Github obviously does not forward them, they are not linked here and also the respective mail notification does not have them attached.

However, if I'm right and the unit pdf2json returns is typography points, then the number you are looking for is 2.83446712018. That is the number of points that make up a millimetre. Divide your coordinates by that and you have their relative position regarding the origin given in mm. Moving the origin around is also not complicated. If it is in the bottom left, then you simply subtract your y components from the total height of your medium and origin is in the top left. Same goes for x to get it on the right.

Maybe the pdf2json coordinates are given in pixels but I doubt that. Without knowing the dpi value for this calculation there is no chance to reconstruct the original physical layout. But you should be able to find that out in the code. And well, there is some code that knows the [concept of dpi](https://github.com/modesty/pdf2json/blob/master/lib/pdfunit.js#L10).

**Comment by SPlatten** [comment]
Thank you, I will investigate tonight and report back.

**Comment by RST-J** [comment]
Probably you should yourself look deeper into the concept of dpi. There is no THE dpi. It is a composed measure depending on typography points and area.
I cannot really extract a meaning or intent from the question.

Maybe this helps: Your screen right in front of you has a certain, fixed number of dpi. Now there are very clever people who find things too large/too small on the screen. Next they change the dpi in the system settings and are happy ... until they print something out and find it be in different size than it appeared to be when shown with 100% zoom on the screen. That is because they abuse dpi for zooming purpose.

**Comment by SPlatten** [comment]
OK, Sorry if I'm being dumb here, but in my example PDF which I have produced the JSON for, the height of the page is 52.618 and the width is 37.205.

This is an A4 document, I have a title in the centre / top of the page, the JSON for this entry is:

        "text": [{"x": 15.639,
	    	      "y": 4.417,
		     "w": 8.218,
		   "sw": 0.32553125,
		   "clr": 0,
		     "A": "left",
		     "R": [{	"T": "Curriculum Vitae",
			        "S": -1,
			      "TS": [0, 49, 1, 0]}]

Using GIMP I open the same PDF, what units should I select in GIMP? 
Do I use '2.83446712018' on the units reported by GIMP or the units displayed in the JSON?
