### ISSUE TITLE
Help...

### ISSUE THREAD

**Issue by SPlatten** [modesty/pdf2json#133]
I've been trying for quiet a while now to figure out how to add a bounding rectangle for each text item.  I thought I'd made some break throughs but the results when applying to pdf2json are still not correct.

I printed text using various font sizes and worked out that the font size is based on (1/72) * FontSize, I then convert this to millimetres.  The results are very accurate, but I do not know how to apply this logic to pdf2json.

In pdffont.js on line 334:

        let oneText = {x: PDFUnit.toFormX(p.x) - 0.25
                      ,y: PDFUnit.toFormY(p.y) - 0.75
                      ,w: PDFUnit.toFixedFloat(maxWidth)
 	                  ,sw: this.spaceWidth //font space width, use to merge adjacent text blocks
                      ,clr: clrId
                      ,A: "left"
                      ,R: [{T: this.flash_encode(text)
                           ,S: this.fontStyleId
                          ,TS: TS}]};

I don't understand why 'w' doesn't have any scaling applied, what units is 'w' in?  

I would like to add x2 and y2 to the object, where x2 is x + (width of text * scalefactor))  and y2 is y + (fontSize * (1/72)).  But whilst y2 seems correct x2 isn't.

Can anyone help ?

**Comment by SPlatten** [comment]
What is the -0.25 and -0.75 about in the x and y?

**Comment by SPlatten** [comment]
My tests and results of what pdf2json outputs in terms of x and y lead me to believe that there is something wrong with the conversion and that the results are wrong.

If I take the x and y returned by pdf2json and the page width and height, in my example, the page width is 37.2 and the page height is 52.612, no idea what units these are in, it seems pdf2json uses something strange, not inches and not mm.

So I take the returned width and height and convert them to the units I need, in this case mm:

        conversion factor X = (A4 page width in mm) / (pdf2json returned width)
        5.64516129032258 = 210 / 37.2

        conversion factor Y = (A4 page height in mm) / (pdf2json returned height)
        5.645099977191515 = 290 / 52.612

I then apply these factors to the x and y returned in the texts array, in my test PDF I have test on the page at 22mm (x) and 45mm (y), pdf2json returns these as 3.051 (x) and 7.8759999999999994 (y)

I then use my conversion factors:

	objText["sx"] = objText["x"] * fltSFX
        17.223387096774193 = 3.051 * 5.64516129032258

	objText["sy"] = objText["y"] * fltSFY
        39.340701741047674 = 6.969 * 5.645099977191515

When I use my ruler on a hard copy of the same PDF, x and y are different, x should be 20mm and y should be 44 mm.

I've tried to figure out what is going wrong and to be honest I do not understand what is going on in lib/pdffont.js, on line 334 it uses the method 'toFormX' to convert the passed x and then subtracts -0.25, on line 335, y is the result of 'toFormY' -0.75.

There are no comments in the file to give any idea of what is going on and what these factors are...can anyone help?  I've made several posts now on this hub and to date I have had no responses, is this mod dead?

**Comment by SPlatten** [comment]
In the end I decided not to use this module as there are way to many unanswered issues, I've download pdf.js and implemented my own solution which works.

**Comment by austenstrine** [comment]
> In the end I decided not to use this module as there are way to many unanswered issues, I've download pdf.js and implemented my own solution which works.

Are you willing to share said solution? XD
I'm feeling the same way about too many unanswered questions, it'd be great to have an alternative
