### ISSUE TITLE
Extract a particular page from pdf.

### ISSUE THREAD

**Issue by anuragpatil94** [modesty/pdf2json#135]
I am successfully able to parse pdf files and write them to a text file with the help of the library. 
But is there _a way to get a particular page from pdf_ instead writing the whole pdf or at least parse and write to a text file just the 1st page of the pdf.

`let fs = require('fs'),
    PDFParser = require("pdf2json");
let pdfParser = new PDFParser(this, 1);
pdfParser.on("pdfParser_dataError", errData => console.error(errData.parserError));
pdfParser.on("pdfParser_dataReady", pdfData => {
    fs.writeFile("content.txt", pdfParser.getRawTextContent());
});
pdfParser.loadPDF("./m/x.pdf");
`

This code will parse the whole pdf and write the output to content.txt
What I am trying to do is just get the **1st page or (any particular page)** of the pdf file instead of the whole file.

**Comment by SPlatten** [comment]
The pages are all stored individually in an array, you can access any page by indexing into the array.

**Comment by anuragpatil94** [comment]
@SPlatten Thanks for quick response. Can you provide an example on how to access a raw data from the particular page? 
I found that Pages are an array of objects using `console.log(pdfData)`. and accessing the page via `pdfData.formImage.Pages[page_number]` which contains 
`var page = {Height,                                                                                                             
                 HLines,                                                                                                                     
                 VLines,                                                                                                                     
                 Fills,                                                                                                                                                                                                                                 
                 Texts,                                                                                                                       
                 Fields,                                                                                                                     
                 Boxsets                                                                                                                    
             };`

**Comment by SPlatten** [comment]
Are you are using the module pdf2json?

As in your post you have access to the information stored on a page, what else do you need?

**Comment by anuragpatil94** [comment]
@SPlatten  Ohh yeah I got it. but there are several breaks even in a single line of pdf when I extract the data
For Example:
**"Phytodegradation is a phytoremediation technology that uses plants to remediate sites contaminated"** 
Above line is a single line in pdf.
which is extracted as
**Phytodegradation is a phytoremedia
tion technology that uses
plants to remediat
e sites**
Exactly as above and for every line, there are such breaks.
Is there any way to avoid this? and just get a single line completely every time.
Also is there a way to determine where the paragraph ends? 

Thanks in advance.

**Comment by SPlatten** [comment]
This may or may not be what you want to hear...due to lack of support on this module I downloaded the module https://github.com/mozilla/pdfjs-dist, I was then able to implement my own solution interacting with pdf.js and it's API, this works perfectly.

**Comment by anuragpatil94** [comment]
Thanks, @SPlatten  I will look into it
