### ISSUE TITLE
Calling an asynchronous function witho ut callback is deprecated

### ISSUE THREAD

**Issue by huesoamz** [modesty/pdf2json#142]
let fs = require('fs'),
        PDFParser = require("pdf2json");

    let pdfParser = new PDFParser();

    pdfParser.on("pdfParser_dataError", errData => console.error(errData.parserError) );

    pdfParser.on("pdfParser_dataReady", pdfData => {
        fs.writeFile("focus.txt", pdfParser.getRawTextContent());
    });    

  pdfParser.loadPDF(filePath);

(node:8136) [DEP0013] DeprecationWarning: Calling an asynchronous function witho
ut callback is deprecated.

its not longer maintain this method?

**Comment by dharness** [comment]
It's a change to warnings about node's `fs` module:
Change your write to:
```
fs.writeFile("focus.txt", pdfParser.getRawTextContent(), () => {
    console.log('done')
});
```
