### ISSUE TITLE
URL Encoding of text nodes

### ISSUE THREAD

**Issue by bogacg** [modesty/pdf2json#147]
I'm getting proper encoded text when I call `pdfParser.getRawTextContent()`, but generated json data contains text nodes in URL encoding format.

For example a word containing Turkish letters:  **Karşılaştırma**

```
"R": [
    {
        "T": "Kar%C5%9F%C4%B1la%C5%9Ft%C4%B1rma",
    }
]
```
Is there an option to generate json data with text nodes already url decoded?
Thanks

**Comment by VirgilioGM** [comment]
Hi @bogacg.

A workaround could be:
```
for (var i = 0; i < pdfData.formImage.Pages.length; i++){
    for (var j = 0; j < pdfData.formImage.Pages[i].Texts.length; j++){
        pdfData.formImage.Pages[i].Texts[j].R[0].T = decodeURIComponent(pdfData.formImage.Pages[i].Texts[j].R[0].T);
    }
}
```

In fact, my code looks actually like this:
```
pdfParser.on("pdfParser_dataReady", pdfData => {
    var pages = pdfData.formImage.Pages.map((page, idx) => {
        return {page: idx, items: page.Texts.map(text => decodeURIComponent(text.R[0].T))}
    });
});
```

**Comment by jlee474** [comment]
decodeURIComponent!  that's it. Lifee saver 

> Hi @bogacg.
> 
> A workaround could be:
> 
> ```
> for (var i = 0; i < pdfData.formImage.Pages.length; i++){
>     for (var j = 0; j < pdfData.formImage.Pages[i].Texts.length; j++){
>         pdfData.formImage.Pages[i].Texts[j].R[0].T = decodeURIComponent(pdfData.formImage.Pages[i].Texts[j].R[0].T);
>     }
> }
> ```
> 
> In fact, my code looks actually like this:
> 
> ```
> pdfParser.on("pdfParser_dataReady", pdfData => {
>     var pages = pdfData.formImage.Pages.map((page, idx) => {
>         return {page: idx, items: page.Texts.map(text => decodeURIComponent(text.R[0].T))}
>     });
> });
> ```
