### ISSUE TITLE
TypeError [ERR_INVALID_CALLBACK]: Callback must be a function

### ISSUE THREAD

**Issue by aaayushishah** [modesty/pdf2json#191]
My Code =>

let fs = require('fs'),
    PDFParser = require("pdf2json");

let pdfParser = new PDFParser();

pdfParser.on("pdfParser_dataError", errData => console.error(errData.parserError));
pdfParser.on("pdfParser_dataReady", pdfData => {
    fs.writeFile("sampleJSON.json", JSON.stringify(pdfData));
});

pdfParser.loadPDF("samplePdf.pdf");

ERROR =>
TypeError [ERR_INVALID_CALLBACK]: Callback must be a function
    at maybeCallback (fs.js:129:9)
    at Object.writeFile (fs.js:1156:14)
    at PdfParser.pdfParser.on.pdfData (D:\Ayushi\R&D\pdfReader\appp.js:31:8)
    at PdfParser.emit (events.js:182:13)
    at PdfParser._onPDFJSParseDataReady (D:\Ayushi\R&D\pdfReader\node_modules\pdf2json\pdfparser.js:23:9)
    at cls.emit (events.js:182:13)
    at process.nextTick (D:\Ayushi\R&D\pdfReader\node_modules\pdf2json\lib\pdf.js:250:38)
    at process._tickCallback (internal/process/next_tick.js:61:11)

**Comment by aaayushishah** [comment]
replace writeFile code with the below code. 
it worked for me!!
 fs.writeFile("sampleJSON.json", pdfParser.getRawTextContent(), () => {
        console.log(JSON.stringify(pdfData))
    });

**Comment by akramer-zibra** [comment]
`fs.writeFile()` needs a third argument, which should be a function, e.g. like @aaayushishah did in her comment.
```
pdfParser.on("pdfParser_dataError", errData => console.error(errData.parserError) );
pdfParser.on("pdfParser_dataReady", pdfData => {
    fs.writeFile("./pdf2json/test/F1040EZ.json", JSON.stringify(pdfData), (response) => {
        console.log(response);
    });
});
```
You find more about fs.writeFile here: https://nodejs.org/api/fs.html#fs_fs_writefile_file_data_options_callback

**Comment by keremh** [comment]
@aaayushishah thank you! 
It worked for me to :)

**Comment by jlee474** [comment]
> replace writeFile code with the below code. it worked for me!! fs.writeFile("sampleJSON.json", pdfParser.getRawTextContent(), () => { console.log(JSON.stringify(pdfData)) });

Life saver!!!
