### ISSUE TITLE
Expose PDFUnit as a utility class

### ISSUE THREAD

**Issue by robross0606** [modesty/pdf2json#201]
There are _so_ many people confused about how to convert PDFUnit, when the information and algorithms are mostly hidden inside PDFUnit.  This should be enhanced and exposed so people can convert from "PDF unit" back to real world measurements.

**Comment by intervalia** [comment]
Everything Adobe says about PDF Units is they are supposed to be 72. But yours is not 72. What are they?

**Comment by modesty** [comment]
it's exposed as PDFParser.PDFUnit in v3.1.2
