### ISSUE TITLE
Page doesn't have Width property

### ISSUE THREAD

**Issue by jtanadi** [modesty/pdf2json#202]
Is there a reason each `Page` doesn't have a `Width` property, but has a `Height` property? Some of the documents I've needed to process have different page sizes in one document, and it seems odd to me that only each page's height is stored, and not its width. I'm not sure if there's a technical reason for this that I'm not aware of?

In the snippet from `lib/pdf.js` below, only the first page's width is parsed and stored.
```js
    pageParser.parsePage(
      (data) => {
        if (!this.pageWidth)
          //get PDF width
          this.pageWidth = pageParser.width

        let page = {
          Height: pageParser.height,
          HLines: pageParser.HLines,
          VLines: pageParser.VLines,
          Fills: pageParser.Fills,
          ...
        }

     this.pages.push(page)
     ...
```

Storing each page's width is a simple enough modification:
```js
 let page = {
          Width: pageParser.width, // get width for every page
          Height: pageParser.height,
          HLines: pageParser.HLines,
          VLines: pageParser.VLines,
          ...
  }
```

I'd love to PR this if there's no objection.

**Comment by modesty** [comment]
all page objects should have Width property now. If not, upload our PDF please

**Comment by jtanadi** [comment]
Thanks!
