### ISSUE TITLE
Typings? index.d.ts

### ISSUE THREAD

**Issue by tim-rohrer** [modesty/pdf2json#207]
I'm trying to use this with Typescript. Has anyone written an `index.d.ts` for this lib?

**Comment by ManAnRuck** [comment]
this would be awesome!

**Comment by tim-rohrer** [comment]
For those who are interested, I moved on to [this project](https://gitlab.com/autokent/pdf-parse) for which I found some [typings by DefinitelyTyped](https://www.npmjs.com/package/@types/pdf-parse).

However, it isn't clear the autokent project is being  updated either, but at least I can code in TS.

**Comment by thiagon4code** [comment]
Hello, I also use this library and I had to code the typing in my project. 

I will open a pull request as soon as possible.

😄

**Comment by blitzmann** [comment]
Any progress on any of this?

**Comment by bre7** [comment]
https://github.com/minjunk/welstory-menu-pdf-parser/blob/master/src/index.ts

**Comment by agarwal-nitesh** [comment]
https://github.com/agarwal-nitesh/p2jsvc

**Comment by modesty** [comment]
sorry for answering late, typing is added in 3.1.2
