### ISSUE TITLE
Wait for the ".on" function to return

### ISSUE THREAD

**Issue by leonardopn** [modesty/pdf2json#218]
I know it's not the purpose, but I haven't found another place that would know more about the module itself.
I am wanting to see if the following situation is possible:
I have a frontend that sends a pdf to the backend node via a POST, I needed that backend to get the pdf, separate the pages into other pdf's files and then enter pdf2json. For each file I go through the fs module and in each one, I need to get relevant information and save it. So far so good I am able to do, but at the end of all this processing I wanted to send the data treated in the POST response back to the frontend, however when I perform the function "pdfParser.loadPDF (" pdf file ")" I needed to wait for the ".on (" pdfParser_dataReady ")" method ends the whole process before ending the chain and returning the response to the frontend.
I noticed that the purpose of .on was really to be done asynchronously, but I can only send the data after processing with pdf2json. Does anyone know any way to solve this or was the project really meant to be this way?

**Comment by philwu** [comment]
Did you solve it? I saw you closed issue
