### ISSUE TITLE
xmldom dependency issue

### ISSUE THREAD

**Issue by joyarzun** [modesty/pdf2json#234]
Hello

Sorry for the captures but it's better to explain the issue

![image](https://user-images.githubusercontent.com/828211/121567865-0c8e0c00-c9ed-11eb-9b82-6f273e9759c3.png)

![image](https://user-images.githubusercontent.com/828211/121568603-dc933880-c9ed-11eb-9b0c-115ff6b03e26.png)

So in the end, pdf2json has the wrong xmldom version build-in

**Comment by modesty** [comment]
try again with v1.2.3?

**Comment by joyarzun** [comment]
It seems to work. thanks.
