### ISSUE TITLE
Warning: Setting up fake worker; loadMetaData error: TypeError: ... on latest version

### ISSUE THREAD

**Issue by mxs17** [modesty/pdf2json#249]
Hello!

I am getting the following output
```
Warning: Setting up fake worker.
loadMetaData error: TypeError: Cannot read property 'metadata' of null
```
when trying to parse different PDFs with `1.3.0` (tried on Node 14, 15, 16). 
The same example works correctly on `1.2.3`.

Code to reproduce:
```javascript
const fs = require("fs");
const PDFParser = require("pdf2json");

const pdfParser = new PDFParser();

fs.readFile("./sample.pdf", (err, pdfBuffer) => {
  if (!err) {
    pdfParser.parseBuffer(pdfBuffer);
  }
});
```

**Comment by modesty** [comment]
@robross0606 you are right, 1.3.0 needs to be 2.0.0, on it.

**Comment by robross0606** [comment]
I have updated to 2.0.1 and I'm _still_ seeing this message:
```
Warning: Setting up fake worker. 
```
What is it and is there some way to remove it?
