### ISSUE TITLE
Error: Requesting object that isn't resolved yet

### ISSUE THREAD

**Issue by marianorodriguez** [modesty/pdf2json#255]
Hello!

I'm getting an error when trying to parse a document containing emojis
![image](https://user-images.githubusercontent.com/11478307/144620804-601ac420-a761-4dc8-8412-9a6e9a649c86.png)

This is the file that i'm trying to parse: [emojis.pdf](https://github.com/modesty/pdf2json/files/7650319/emojis.pdf)
And here is a minimal sandbox showing the error: https://codesandbox.io/s/thirsty-keller-suglx?file=/src/index.js

The file was originally made using playwright with a headless chromium and printing the page as pdf

**Comment by modesty** [comment]
as the error msg states, emojis is not supported, yet. exception is correctly thrown and caught.

**Comment by marianorodriguez** [comment]
hello @modesty, thanks for the reply. Any chance this could be just a warning and keep parsing the rest of the document instead of throwing error?

**Comment by modesty** [comment]
fix is pushed to feat/eslintNtypescript, will be included in v3.1.3
