### ISSUE TITLE
Cannon't Read Property Num

### ISSUE THREAD

**Issue by varsis** [modesty/pdf2json#26]
```'Warning: Unhandled rejection: TypeError: Cannot read property 'num' of undefined' at Obj.RefSetCache_has [as has] ..... ```

The error occurs in base/core/objs.js, I replaced the line with a hack fix for the time being:

```  has: function RefSetCache_has(ref) {
        return ('R' + ref.num + '.' + ref.gen) in this.dict;
    }```

after:

```  has: function RefSetCache_has(ref) {
      if(ref !== undefined)
        return ('R' + ref.num + '.' + ref.gen) in this.dict;
      else
        return null;
    }```

**Comment by modesty** [comment]
fixed in v1.0.9
