### ISSUE TITLE
Unnecessary console.log

### ISSUE THREAD

**Issue by ana108** [modesty/pdf2json#260]
Ever since I updated from version 1.2.1 to 2.0.0 (current latest)
I'm seeing this in the logs
"to be implemented: contextPrototype.clearRect"

Its not breaking anything, but it does clutter the logs a bit

**Comment by robross0606** [comment]
I'm also seeing this constantly:
```
Warning: Setting up fake worker. 
```
What is it and is there some way to remove it?

**Comment by febkosq8** [comment]
I keep getting

```
Warning: Setting up fake worker.
Warning: TT: undefined function: 133
Warning: Unsupported: field.type of Link
Warning: NOT valid form element
Warning: Unsupported: field.type of Link
Warning: NOT valid form element
Warning: Unsupported: field.type of Link
Warning: NOT valid form element
Warning: Unsupported: field.type of Link
Warning: NOT valid form element
Warning: TT: undefined function: 133
```
I am getting the pdf output as expected. But I find no way to suppress these warnings.

**Comment by robross0606** [comment]
Same.  Was surprised to get this when upgrading to path audit CVE.  This warning taints our unit test output.  Is there no way to turn this off?

**Comment by alvis** [comment]
Same here

**Comment by choujar** [comment]
Has anyone found a solution to this?

**Comment by AlexFransis** [comment]
Getting the same issue here

**Comment by febkosq8** [comment]
I found the following from some other issue, but it works in suppressing the consoles outputs(mostly)

```js
import pdfJsonNodeUtil from "util";
if (typeof pdfJsonNodeUtil["verbosity"] === "function") {
	pdfJsonNodeUtil["verbosity"](0);
}```

**Comment by alvis** [comment]
I have seen that before. This package injects a verbosity field in `node:util` builtin.
It's certainly tacky and the only way to disable it is by hack the field in `node:util` builtin...

**Comment by LunaSquee** [comment]
I was also confused as to why `parseBuffer` takes in a `verbosity` number if it does nothing at all 😕

**Comment by alexmga78** [comment]
@LunaSquee for me setting ```pdfParser.parseBuffer(buffer, 0)``` is suppressing warnings, still not suppressing errors though
pdf2json: 3.1.5

**Comment by DhanushNehru** [comment]
Thanks @alexmga78 this setting `pdfParser.parseBuffer(buffer, 0)` aleast helps to supress some of the warnings

**Comment by petero-dk** [comment]
I had troubles with these settings, and just realized that setting verbosity to 0 does nothing it will evaluate to false in these two lines:

https://github.com/modesty/pdf2json/blob/8554a3a2ce5b1074db759a2d6546b9920d45c7ea/pdfparser.js#L266

and

https://github.com/modesty/pdf2json/blob/8554a3a2ce5b1074db759a2d6546b9920d45c7ea/pdfparser.js#L238

And the correct solution is to send -1

```
pdfParser.loadPDF(filePath, -1);
```

or 

```
pdfParser.parseBuffer(buffer, -1)
```
