### ISSUE TITLE
Error: Invalid XRef stream

### ISSUE THREAD

**Issue by failvaliev** [modesty/pdf2json#274]
[Счет для покупателя №00001410 от 26.05.2021 17_13.pdf](https://github.com/modesty/pdf2json/files/9055045/00001410.26.05.2021.17_13.pdf)
Error reading this file: Invalid XRef stream.

![изображение](https://user-images.githubusercontent.com/92177563/177559538-eeb0d7a5-2c2a-4106-90ef-396ff204ddcf.png)

const pdfParser = new PDFParser(this, 1);
      pdfParser.on("pdfParser_dataError", errData => {
         console.error(errData.parserError)
      })
      pdfParser.on("pdfParser_dataReady", pdfData => {
        //....
      });
      pdfParser.loadPDF(file);

**Comment by Tobias-Keller** [comment]
[3408_7747_1677535747076.pdf](https://github.com/modesty/pdf2json/files/10848129/3408_7747_1677535747076.pdf)
having the same problem with this file

**Comment by VitorBrangioni** [comment]
any update?
