### ISSUE TITLE
 parserError: 'bad XRef entry'

### ISSUE THREAD

**Issue by bell2041** [modesty/pdf2json#277]
Getting an error` parserError: 'bad XRef entry'` on attached PDF on latest 2.0.1, please advise. 

Here is the link for the PDF File
http://a820-ecbticketfinder.nyc.gov/GetViolationImage?violationNumber=0071176995

**Comment by simlu** [comment]
Same issue here, unclear what's going on :grimacing:

**Comment by modesty** [comment]
cannot repo with v3.1.2
PDF is saved to test/pdf/misc, covered by `npm run test:misc`
