### ISSUE TITLE
Failed to load pdf2json as ES Module

### ISSUE THREAD

**Issue by arribbar** [modesty/pdf2json#282]
**Environment**
- node: 14.18.3
- Using NestJS / Typescript
- pdf2json version: 2.1.0

**Bug**
When I try to run project by importing the module
```
import fs from 'fs';
import PDFParser from 'pdf2json';
```

I have this error
```
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: project/node_modules/pdf2json/pdfparser.js
require() of ES modules is not supported.
require() of project/node_modules/pdf2json/pdfparser.js from project/src/script/script.service.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename pdfparser.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from project/node_modules/pdf2json/package.json.

    at new NodeError (internal/errors.js:322:7)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1102:13)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at Object.<anonymous> (project/src/script/script.service.ts:2:1)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/load
```

Do you have any idea how to solve this issue ? 

Thanks a lot

**Comment by Guccieii** [comment]
In your `tsconfig.json` try to set
```
"compilerOptions": {
 ...
 "module": "NodeNext"
 ...
}
```

If this breaks the rest of your project consider to lock the version of this library to v2.0.1.
```"pdf2json": "~2.0.1"```

Unfortunately this is a breaking change and shouldn't be treated as a minor release.

**Comment by ryanrosello-og** [comment]
Hi, i'm also encountering this issue when attempting to upgrade from v2.0.1 to 2.1.0.  The reason why we are upgrading was due to Dependabot alert triggered in our project around a flaw in `xmldom` package which I traced back to `pdf2json` package

![2022-10-19_14-15-00](https://user-images.githubusercontent.com/50574915/196596478-5b5cac9e-abc9-4772-a16f-639f6376d448.png)
![2022-10-19_14-16-33](https://user-images.githubusercontent.com/50574915/196596481-def899e0-e0a7-4290-bdb3-6eab9abe5d88.png)

Unfortunately, updating the `tsconfig.json` file will not help our situation.

**Comment by modesty** [comment]
can you try with v3.0.0?

**Comment by ryanrosello-og** [comment]
I've tried with version 3.0.0

I see this error when trying to run my Playwright tests:

```javascript
Running 0 tests using 0 workers
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: c:\_repo\redacted-Automation-Playwright\node_modules\pdf2json\pdfparser.js
require() of ES modules is not supported.
require() of c:\_repo\redacted-Automation-Playwright\node_modules\pdf2json\pdfparser.js from c:\_repo\redacted-Automation-Playwright\support\helpers\pdfHelpers.ts is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename pdfparser.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from c:\_repo\redacted-Automation-Playwright\node_modules\pdf2json\package.json.


    at new NodeError (internal/errors.js:322:7)
    at Module._extensions..js (internal/modules/cjs/loader.js:1102:13)
    at Object.t.<computed>.tu._extensions.<computed> [as .js] (c:\_repo\redacted-Automation-Playwright\node_modules\@playwright\test\lib\utilsBundleImpl.js:16:1010)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at Object.<anonymous> (c:\_repo\redacted-Automation-Playwright\support\helpers\pdfHelpers.ts:8:40)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Module.A._compile (c:\_repo\redacted-Automation-Playwright\node_modules\@playwright\test\lib\utilsBundleImpl.js:16:994)
    at Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Object.t.<computed>.tu._extensions.<computed> [as .ts] (c:\_repo\redacted-Automation-Playwright\node_modules\@playwright\test\lib\utilsBundleImpl.js:16:1010)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
```

I'm using `pdf2json` as follows:

***pdfHelpers.ts***
```typescript
import PDFParser from 'pdf2json';

export default class PdfHelpers {
  private _pdfParser: PDFParser;

  constructor() {
    this._pdfParser = new PDFParser();
  }

  async getPDFContents(options: {pdfFilePath: string}): Promise<any> {
    return new Promise((resolve, reject) => {
      this._pdfParser.on('pdfParser_dataError', (errData: {parserError: any}) =>
        reject(errData.parserError)
      );
      this._pdfParser.on('pdfParser_dataReady', (pdfData) => {
        resolve(pdfData);
      });

      this._pdfParser.loadPDF(options.pdfFilePath);
    });
  }
}

```
in the tests

```typescript
    const pdfContents = await helpers.pdfHelpers.getPDFContents({pdfFilePath});
    expect(pdfContents.Meta.Author, 'PDF meta information was incorrect').toEqual('redacted');
```

**Comment by ryanrosello-og** [comment]
I've also created a public repo here => https://github.com/ryanrosello-og/pdf2jsonissue/blob/main/README.md
After cloning the repo, run:

`npm i`

Run tests:

`npx playwright test`

**Comment by KilianCM** [comment]
Same problem as @ryanrosello-og updating from 2.0.1 to 3.0.0 with ES module import:
`import PDFParser from 'pdf2json';`

_Moreover, the code example in the README is wrong:
`import PDFParser from "./pdfparser.js";`
This cannot work except in the library context itself._

**Comment by mcdado** [comment]
Why has v3 been released only as an ES Module without a strategy for CommonJS workflows which I bet are the large majority? Changing `compilerOptions` does not work for people who simply run Node.js code without compilation.

How about something like building both an `.mjs` and `.cjs` file for builds? Leaving the 2.x with critical security flaws and not offering an upgrade seems a bit _strange_ to me.

**Comment by hanseltime** [comment]
I want to echo @mcdado - Cutting over to ESM for large projects is a nightmare and can require tons of testing.

Is there a reason we're not doing a roll-up of both? or making v2 CJS only?  2.1.0 is set to module as well right now...

**Comment by rubnogueira** [comment]
@hanseltime had that issue as well. locking at 2.0.1 solved my issue.

**Comment by VictorEB** [comment]
This error still occurs on version 2.1.0 and higher. It's a real blocker for the CVE fix.
Is there a workaround or an estimation for the fix?

**Comment by Rahien** [comment]
Our way around this was to use dynamic imports, it works, but isn't the greatest solution as for instance jest really doesn't like them at the moment: https://github.com/nodejs/node/issues/35889

**Comment by neotrow** [comment]
@Rahien 

Can you make an example of such a dynamic import? I tried that approach but get same error:

```
const pdf = await import("pdf2json")
```

gives me 

```
require() of ES Module .....\node_modules\pdf2json\pdfparser.js from ......\cypress.config.ts not supported.

Instead change the require of pdfparser.js in ......cypress.config.ts to a dynamic import() which is available in all CommonJS modules.
```

**Comment by modesty** [comment]
@ryanrosello-og can you add "type": "module" to https://github.com/ryanrosello-og/pdf2jsonissue/blob/main/package.json and try again?

**Comment by ryanrosello-og** [comment]
@modesty after adding `"type":"module"` into the `package.json`, I'm now seeing the error below:
![image](https://github.com/modesty/pdf2json/assets/50574915/a06a0e6e-c288-4124-ae5f-bdb9c5a3b5bd)

**Comment by modesty** [comment]
after adding "type":"module" in package.json, change dependencies to "pdf2json": "^3.0.4", 
run the following command for testing:

```
rm -rf node_modules && rm package-lock.json && npm i && npx playwright install && npx playwright test
```

it loads pdf2json as es module correctly, and 3 tests passed
 
<img width="1046" alt="Screenshot 2023-06-04 at 11 43 20 AM" src="https://github.com/modesty/pdf2json/assets/865809/44ce87d2-9c2e-4df8-9eb3-8448d89c0d21">

**Comment by modesty** [comment]
make sure node version >= 18.12.1, and the importing project's package.json has "type": "module". ^^

**Comment by ryanrosello-og** [comment]
@modesty LGTM, thanks for fixing this.

**Comment by doczoidberg** [comment]
is there a workaround when using node 16?

I use firebase functions

**Comment by zozoyasuda** [comment]
I have this issue as well with node21 and using v3.1.1. Locking it to v3.0.5 fixes it.
