### ISSUE TITLE
import {Blob} from "buffer" issue

### ISSUE THREAD

**Issue by SGtaleGY** [modesty/pdf2json#289]

**Comment by SGtaleGY** [comment]
Alwasy got error when upgrade form 2.0.1 to 3.0.1.
import {Blob} from "buffer":
The requested module 'buffer' does not provide an export name'Blob'

After commented out pdf.js 
import {Blob} from "buffer":

works fine.

Please fix this issue

**Comment by modesty** [comment]
update node to latest LTS 18.12.1 and pull the latest, it should be fixed.
