### ISSUE TITLE
No more info CLR and OC field always undefined

### ISSUE THREAD

**Issue by jac0bi** [modesty/pdf2json#293]
thank you Modesty for your work. I have a problem hope you can help me. In the latest versions (>1.2.5) the clr field (text color) is no longer present and the OC field is always undefined. Is it still possible to have information about text  color? Thanks again

**Comment by modesty** [comment]
can you upload a PDF?

**Comment by jac0bi** [comment]
You can replicate this problem for example using the pdf linked below. Maybe am I
 doing something wrong? Thank you

[pdfpac.pdf](https://github.com/modesty/pdf2json/files/10257600/pdfpac.pdf)

**Comment by modesty** [comment]
please pull the latest and run `npm run parse-tc" to test, should work now.

**Comment by jac0bi** [comment]
Thank a lot, now work smoothly

**Comment by modesty** [comment]
v3.0.2 released.
