### ISSUE TITLE
Import {Blob} from 'buffer' Issue Render Deployment

### ISSUE THREAD

**Issue by Scuba2105** [modesty/pdf2json#294]
I have developed a very small web app which uses pdf2json as a nested dependency. The app works fine in my development environment but when I try to deploy to Render it produces an error in pdf.js at line 7 about being unable to import {Blob} from 'buffer'. I see the module was recently updated and I have tried the latest version of both NodeJs and pdf2json. Do you know what could be causing this?

**Comment by modesty** [comment]
what's the error message? what's node version you're using?

**Comment by Scuba2105** [comment]
The error is Module '"buffer"' has no exported member 'Blob'. I am using
Node v18.12.1 and pdf2json v3.0.2. However since then I have deployed the
app to Cyclic without any issues. I am very much a newbie with Node so I
have no idea why it works within VSCode and deploys to Cyclic but the error
occurs when trying to deploy with Render.

Regards,

Steve

**Comment by andreash** [comment]
+1

**Comment by modesty** [comment]
make sure the Render deployed environment has the same version of node that VSCode uses

**Comment by modesty** [comment]
env or version issue, close.
