### ISSUE TITLE
Console WARN SPAM 

### ISSUE THREAD

**Issue by NatanBarbosa2** [modesty/pdf2json#295]
![image](https://user-images.githubusercontent.com/89656623/209998584-373edd2d-aa1b-41c6-99e7-39ab282be703.png)

I can disable this? 

version:   "pdf2json": "^2.0.0"

**Comment by modesty** [comment]
try '-s' command line param

**Comment by NatanBarbosa2** [comment]
But this is in file (require = "pdf2json)... not CLI

**Comment by jeffstieler** [comment]
It would be nice to add a `verbosity` argument to the `parseBuffer()` function for non-CLI usage.

For now I'm hacking around it by doing:
```javascript
// pdf2json adds methods to util
import pdfJsonNodeUtil from 'util'
// reduce the verbosity of pdf2json
if (typeof pdfJsonNodeUtil['verbosity'] === 'function') {
    pdfJsonNodeUtil['verbosity'](0)
}
```

**Comment by NatanBarbosa2** [comment]
thank you! :)
