### ISSUE TITLE
Not able to convert pdf which has identity-h encoding 

### ISSUE THREAD

**Issue by bhalani97** [modesty/pdf2json#297]
Unexpectedly, I have got the pdf which has identity-h encoding and when I convert this to text based JSON I am getting some weird non readable text.
It seems this library does support such type of encoding.
Can we please support this ?
<img width="1085" alt="pdf-font" src="https://user-images.githubusercontent.com/40469020/222176094-d13a6040-47ba-444d-9e38-51c7af88954f.png">

**Comment by modesty** [comment]
can you upload the example PDF?

**Comment by modesty** [comment]
no reply. close.
