### ISSUE TITLE
Node.js Server got stuck when parsing specific PDF while it is working for other PDFs

### ISSUE THREAD

**Issue by pedrodev033** [modesty/pdf2json#321]
when trying to call this function `this.PDFParser.parseBuffer(PDF)`
server got stuck. even setTimeout is not working and not getting api call. overall server freeze and I had to restart server. 
Appreciate the help.

**Comment by modesty** [comment]
can you upload the PDF file?

**Comment by abhithkba** [comment]
same issue.
here is the pdf file[
[21583473018.pdf](https://github.com/modesty/pdf2json/files/14945892/21583473018.pdf)
](url)
