### ISSUE TITLE
TypeError: pdf2json_1.default is not a constructor

### ISSUE THREAD

**Issue by kafraymundo** [modesty/pdf2json#326]
Hi,
after I did the npm install and run my code (I'm trying to parse a pdf with acroform and validate the value in the fields) but it wouldn't continue due to the TypeError below. 
Please help!

![image](https://github.com/modesty/pdf2json/assets/79170601/9bc9f089-2be9-4739-a0be-9e084a52e26e)

Test code:
![image](https://github.com/modesty/pdf2json/assets/79170601/948e4dab-a291-4956-9695-68c8b4c203cc)

**Comment by nico75005** [comment]
Did you find a solution to your problem?

**Comment by Akifcan** [comment]
you can try this: 
```
import * as PDFParser from 'pdf2json'

 const pdfParser = new (PDFParser as any)(null, 1)

    pdfParser.on('pdfParser_dataError', (errData: any) =>
      console.error(errData),
    )
    pdfParser.on('pdfParser_dataReady', () => {
      console.log(pdfParser.getRawTextContent())
    })
```

Note: I'm using nest.js

**Comment by BenteaB** [comment]
in my case, the issue was fixed after adding `"esModuleInterop": true,` in `tsconfig.json`
