### ISSUE TITLE
Is the auto-merge broken text blocks capability active in the last stable version (3.0.5)?

### ISSUE THREAD

**Issue by Alb93** [modesty/pdf2json#336]
I'm experiencing some broken text blocks problems with the latest version of the library. 

The pdf looks like this 

<img width="226" alt="image" src="https://github.com/modesty/pdf2json/assets/11390668/a92be469-d564-435a-8c92-caffd30aa338">

and this is what I'm getting, as an example:
`{
                    "x": 13.214,
                    "y": 5.237,
                    "w": 2.542,
                    "oc": "#00416e",
                    "sw": 0.44271875,
                    "A": "left",
                    "R": [
                        {
                            "T": "QUA",
                            "S": -1,
                            "TS": [
                                0,
                                13.72,
                                1,
                                0
                            ]
                        }
                    ]
                },
                {
                    "x": 14.743,
                    "y": 5.237,
                    "w": 4.115,
                    "oc": "#00416e",
                    "sw": 0.44271875,
                    "A": "left",
                    "R": [
                        {
                            "T": "DRO%20RS",
                            "S": 9,
                            "TS": [
                                0,
                                12,
                                1,
                                0
                            ]
                        }
                    ]
                },`

Is there any way to activate the auto-merging step by using the library on a node environment? Is there any way to eventually tune it? Thank you!

**Comment by modesty** [comment]
can you upload the PDF?

**Comment by Alb93** [comment]
From the output it seems that the fontsize is (strangely) different. "QUA" is [ 0, 13.72, 1, 0 ] and "DRO RS" is [ 0, 12, 1, 0 ]. This is something that can be seen also by opening the PDF with a PDF reader. So is it probably a printing problem more than a merging one?
How does the merging work?

**Comment by modesty** [comment]
the `-m` option in command line will turn on PROCESS_MERGE_BROKEN_TEXT_BLOCKS, tried it?
