### ISSUE TITLE
Cloudflare Worker issue with Could not resolve "fs/promises"

### ISSUE THREAD

**Issue by GRiDD** [modesty/pdf2json#339]
Getting error while trying to use cloudflare Worker.

<img width="1613" alt="image" src="https://github.com/modesty/pdf2json/assets/4369732/a7d3a416-c8f1-4881-beed-c7e95982725b">

✘ [ERROR] Could not resolve "fs/promises"

    node_modules/pdf2json/dist/pdfparser.js:3:25:
      3 │ import { readFile } from 'fs/promises';
        ╵                          ~~~~~~~~~~~~~

`{
	"name": "pdf2text",
	"version": "0.0.0",
	"private": true,
	"scripts": {
		"deploy": "wrangler deploy src/index.ts",
		"dev": "wrangler dev",
		"start": "wrangler dev",
		"test": "vitest run"
	},
	"devDependencies": {
		"@cloudflare/workers-types": "^4.20240423.0",
		"wrangler": "^3.0.0"
	},
	"dependencies": {
		"pdf2json": "^3.1.0"
	},
	"overrides": {
		"@types/node": "20.8.3"
	}
}
`

**Comment by modesty** [comment]
what does `node -v` show?

**Comment by GRiDD** [comment]
`node -v`
v20.9.0

**Comment by modesty** [comment]
Cloudflare Worker has limited support for node API: https://developers.cloudflare.com/workers/runtime-apis/nodejs/
tried `import { readFile } from 'node:fs/promises'` ?

**Comment by GRiDD** [comment]
For now, I added 
import { readFile } from 'node:fs/promises'
to node_modules/pdf2json/dist/pdfparser.js:3:25:
Now, getting more error. 

I looks like running the pdf2json not possible with CF workers yet. 

<img width="990" alt="image" src="https://github.com/modesty/pdf2json/assets/4369732/99c8c8e7-5310-4afa-a479-5159221d579c">

**Comment by modesty** [comment]
try to change:
- node_modules/pdf2json/dist/pdfparser.js: 
  - `import { readFile } from 'node:fs/promises';`
  - `import { fileURLToPath } from 'node:url';`
  - `import { Blob } from 'node:buffer';`
- also in your src/index.ts:
  - `import { PDFParser } from 'pdf2json;`
