### ISSUE TITLE
no such file or directory - pkinfo.js 

### ISSUE THREAD

**Issue by leermao** [modesty/pdf2json#344]
![image](https://github.com/modesty/pdf2json/assets/11629887/84c96e82-a869-47bf-bf48-773f506b08df)

I tried to check it out. I think the question is here

![image](https://github.com/modesty/pdf2json/assets/11629887/73adcb6b-66fc-41ce-9d85-597dcd1eb095)

I have a feeling it's similar to this problem
https://github.com/modesty/pdf2json/issues/330

**Comment by modesty** [comment]
dup #343, fix is in feat/eslintNtypescript, will be part of v3.1.3
