### ISSUE TITLE
FATAL ERROR: JavaScript heap out of memory

### ISSUE THREAD

**Issue by ruixiaozi** [modesty/pdf2json#356]
My app works fine on smaller PDFs, but when I try on the one I need (200MB, 400 pages that I'm breaking into many), the Node app goes north of 1.6GB ram and then crashes and the output makes me think the cause is in pdffont.js. If it's relevant, I do embed fonts in my PDFs.

**Comment by modesty** [comment]
try to increase the allowed heap size when launch node process, like `--max_old_space_size=4096`.
