### ISSUE TITLE
cli/pdfparser_cli.js: No such file or directory

### ISSUE THREAD

**Issue by carolsos** [modesty/pdf2json#362]
hello , when I run the command"npm run test:forms" , appear error "bin/cli/pdfparser_cli.js: No such file or directory".When I check the pdf2json/bin, I find bin just had one item "pdf2json.js". When I click in that js, I find "import PDFCLI from "./cli/pdfparser_cli.js";",so the current document miss the pdfparser_cli.js?

**Comment by modesty** [comment]
run `npm run build` first.
