### ISSUE TITLE
[Urgent] Getting stuck when parsing PDF with parseBuffer/loadPDF

### ISSUE THREAD

**Issue by pedrodev033** [modesty/pdf2json#364]
Hello support, 
I was using this lib for parsing invoice PDF but getting stuck when parsing one PDF. Is there any chance to get this resolved asap?

**Comment by modesty** [comment]
what's the error and PDF?

**Comment by pedrodev033** [comment]
thanks for your reply, can I share the PDF in private?

**Comment by ummm288** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by modesty** [comment]
no error msg, not PDF shared, close.
