### ISSUE TITLE
No way for consumer to handle crypto related errors when calling loadPdf()

### ISSUE THREAD

**Issue by thealexbaron** [modesty/pdf2json#43]
Currently base/core/crypto.js calls `error()` on errors. There is no callback for catching these errors, and the errors don't emit to `pdfjs_parseDataError`.

Here is the PDF causing the error: https://drive.google.com/file/d/0B3yADm5p-GRCRExYVXFjTnhvQ2c/view?usp=sharing

**Comment by modesty** [comment]
fixed in v1.1.1.
