### ISSUE TITLE
encoding issues 

### ISSUE THREAD

**Issue by wanghaisheng** [modesty/pdf2json#47]
i hava a pdf file like this 

[习近平同津巴布韦总统穆加贝举行会谈_国内新闻_环球网.pdf](https://github.com/modesty/pdf2json/files/49532/_._.pdf)

i can get the chinese character successfully ,but text in  the following pdf file 
[1.pdf](https://github.com/modesty/pdf2json/files/49533/1.pdf)

,only get 
![2015-12-02 17-01-20](https://cloud.githubusercontent.com/assets/2363295/11527271/f2443030-991a-11e5-86d3-2f45609caa56.png)

does this caused by pdf file encoding or something else?

**Comment by modesty** [comment]
The garbled text output is caused by embedded subset font, which is not supported. One workaround is to re-generate the PDF with standard non-embedded fonts, the parser should be able to output correct text. Close.

**Comment by wanghaisheng** [comment]
@modesty  suppose all i get is a pdf like this ,how to re-generate the PDF with standard non-embedded fonts?

**Comment by wanghaisheng** [comment]
@modesty    i notice your fork pdf.js is  v1.1.4  which latest version is  1.6.210
does this embedded subset font   problem be  fixed by the later commit of pdf.js
