### ISSUE TITLE
Checkbox status is always false

### ISSUE THREAD

**Issue by zat619** [modesty/pdf2json#48]
I tried extracting the fields of PDF which is already filled out with data. After extracting i can get all textfields available along with saved data in each fields. But in case of checkboxes or radio buttons, checked status is always false. Maybe i missed something out?

**Comment by modesty** [comment]
The parser only parse checkbox's id and position, not including value, which is user input. See "Interactive Forms Elements" section in readMe.md for more details.

**Comment by elliots** [comment]
The values of text fields are provided (which is also user input), shouldn't the value for checkboxes appear too?

**Comment by elliots** [comment]
Sorry, can't remember now.

**Comment by Glavin001** [comment]
Thanks for your replies!

@karthiknk : Something like https://linux.die.net/man/1/pdftk using `dump_data_fields`? Any more information or sample code would be greatly appreciated. Thanks in advance!

**Comment by karthiknk** [comment]
@Glavin001 @toddmurphy  Yes i exported data using dump_data_fields.

Logic is simple
pdf2json fails only in fetching checkbox and radio button values(as if they are checked) but fields are identified anyway. So save the complete extracted fields using pdf2json in an array. Then process the same pdf using pdftk. Then compare the checkbox and radio button id's with pdf2json values to save the values

Attached the code i used. It is a cakephp framework code
As i said not best case but it works in extracting most radio and checkbox values
Start with function extractdata

Hope helps you

[RemoteController.zip](https://github.com/modesty/pdf2json/files/1914235/RemoteController.zip)

**Comment by Glavin001** [comment]
Thank you very much, @karthiknk !

**Comment by rvillanueva** [comment]
For anyone who comes across this in the future, checkbox value is actually accessible in the existing code. I've made a fork for my use case. It's not fully tested yet, but you can see an example below of how to access the value without adding a completely new library.

https://github.com/rvillanueva/pdf2json/commit/c3b246cb77df9c88fbcf29f680eb49b7d51a8357

Relevant to #92

**Comment by AleksanderPopov** [comment]
Hey guys, i also did something like @rvillanueva , but more general and stupid (im just adding 'value' property, instead of comparing to specific value), here are the commits:

https://github.com/AleksanderPopov/pdf2json/commit/09594fd4e545da66d6c160198b2a76cd81b2938d
https://github.com/AleksanderPopov/pdf2json/commit/72cc5a4337ffdce76578897fc35672692eccea31

I an create PR for that changes, if needed.
