### ISSUE TITLE
_onPFBdataReady not defined error 

### ISSUE THREAD

**Issue by shashanksmf** [modesty/pdf2json#49]
var nodeUtil = require("util"),
            fs = require('fs'),
            _ = require('underscore'),
            PDFParser = require("./pdfparser");

        var pdfParser = new PDFParser();

        pdfParser.on("pdfParser_dataReady", _.bind(_onPFBinDataReady, self));

        pdfParser.on("pdfParser_dataError", _.bind(_onPFBinDataError, self));

    //    var pdfFilePath = _pdfPathBase + folderName + "/" + pdfId + ".pdf";

var pdfFilePath = 'ibpsrrb2012.pdf';
        pdfParser.loadPDF(pdfFilePath);

        // or call directly with buffer
        fs.readFile(pdfFilePath, function (err, pdfBuffer) {
          if (!err) {
            pdfParser.parseBuffer(pdfBuffer);
          }
        })

When i fire the command npm mypdf.js i get the following error
pdfParser.on("pdfParser_dataReady",_.bind<_onPFBinDataReady,self>)

refrence error _onpfbindataready is not defined

**Comment by frenchbread** [comment]
Same error.

**Comment by modesty** [comment]
readme.md updated.
