### ISSUE TITLE
Errors after parsing are getting eaten by library

### ISSUE THREAD

**Issue by IanShoe** [modesty/pdf2json#54]
I have run into a case where I complete a successful pdf parsing, but have an error down the road in my app that gets caught within the parser library. The problem is that the library actually ends up catching the error on [line87](https://github.com/modesty/pdf2json/blob/master/base/shared/util.js#L874-L876) and eating it. I am given no indicators as to what happened or the ability to handle it properly in my app.

Here's a script that will demonstrate parsing a pdf, and then intentionally throwing an error.
https://gist.github.com/IanShoe/e92ee20f4862b187f9ae

**Comment by modesty** [comment]
fixed in v1.1.1.
