### ISSUE TITLE
Missing ) after argument error

### ISSUE THREAD

**Issue by ethanblewb** [modesty/pdf2json#56]
Hi guys , 

/usr/local/lib/node_modules/pdf2json/lib/p2jcmd.js:49
        fs.writeFile(fieldsTypesPath, JSON.stringify(pJSON), err => {
                                                             ^^^

SyntaxError: missing ) after argument list

I'm new to node and javascript, currently i faced this problem when i tried to execute pdf2json directly from shell. What is the "=>" function anway. All the codes with this "=>" is giving me error, including the examples

Thanks

**Comment by raineroviir** [comment]
=> is the es6 function syntax
if you want to run it in your shell you need babel-node

**Comment by ethanblewb** [comment]
Thanks, i think i solved it, my version too old haha
