### ISSUE TITLE
Error: stream must have data

### ISSUE THREAD

**Issue by raineroviir** [modesty/pdf2json#57]
```Error: stream must have data
    at error (eval at <anonymous> (/Users/raineroviir/best-scraper/node_modules/pdf2json/lib/pdf.js:60:6), <anonymous>:193:7)```

Not sure why this is happening. How do I resolve this? In my console.log I see the file loads successfully but this comes up right afterwards

**Comment by modesty** [comment]
can you upload the pdf?

**Comment by raineroviir** [comment]
I found it happens because the file didn't finish downloading first. Sorry about that was just my bad.  The pdf url  `http://www.patrick.af.mil/shared/media/document/AFD-070716-028.pdf`

I had a real question though, I have trouble interacting with the pdfParser API, not able to get getRawTextContent working or really any of the APIs called when the data is ready to be parsed.

I assume to get the data ready to parse, we wait for the async `loadPDF()` to finish?

**Comment by raineroviir** [comment]
It looks like I'm trying to parse a PDF that has no text content. My bad! I'll close the issue
