### ISSUE TITLE
Offering an ES5 Version

### ISSUE THREAD

**Issue by joelzimmer** [modesty/pdf2json#58]
It'd be amazing for projects that aren't using node4 to be able to use this project without needing harmony bindings - would you be able to offer an es5 version of this package?

**Comment by modesty** [comment]
All new features are built with node 4+ and ES6. If you need to run it with an older version of node, please use v0.7.1.

**Comment by joelzimmer** [comment]
I'd really rather this weren't just closed - we're using node 0.12.7 and can't simply downgrade or app (or upgrade our app in the short run either) - wouldn't it be easier and increase usage to provide a `dist` version of the project that can be installed by anyone?
