### ISSUE TITLE
Replace underscore with lodash for improved speed

### ISSUE THREAD

**Issue by vlasky** [modesty/pdf2json#74]
I see this project uses the [underscore](http://underscorejs.org/) library. 

[Lodash](https://lodash.com/) is known to run faster and it is usually just a simple drop-in replacement for underscore.

For a task as heavy as PDF processing, it could result in significantly improved speed.

**Comment by modesty** [comment]
Good point. Stay tuned.

**Comment by modesty** [comment]
done in v1.1.7
