### ISSUE TITLE
PDF page size

### ISSUE THREAD

**Issue by NickNaso** [modesty/pdf2json#90]
Hi,
i'm trying to get width and height of my pdf files, but as reported in this issue https://github.com/modesty/pdf2json/issues/4 i get a value in "Form Unit". I need the width and height express in points, inch or mm.  How can i solve this problem?
Here report my code:
```javascript
'use strict';
const PDFParser = require('pdf2json');
let pdfParser = new PDFParser();

pdfParser.on("pdfParser_dataError", function (err) {
  console.log(err);
});

pdfParser.on("pdfParser_dataReady", function (data) {
  console.dir(data, {depth: null});
});

pdfParser.loadPDF("my-pdf-file.pdf");

```
And here my output:
![screenshot from 2016-09-26 18-08-31](https://cloud.githubusercontent.com/assets/387506/18842116/48b8a75e-8414-11e6-8613-8635b14b02f1.png)
Thanks in advance,
Nick

**Comment by NickNaso** [comment]
Thanks to all, but at the end i found the answer analyzing this file https://github.com/modesty/pdf2json/blob/master/lib/pdfunit.js  where are defined properties and method to obtain the height and width for pdf. 
Nick

**Comment by robross0606** [comment]
@NickNaso can you provide some details on how you used pdfunit.js to get your answer?
